CREATE TABLE ISSUESLISTS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) CHARSET utf8 NOT NULL
);

CREATE TABLE ISSUES
(
    ID SERIAL PRIMARY KEY,
    ISSUESLISTS_ID BIGINT UNSIGNED NOT NULL,
    SUMMARY VARCHAR(100) CHARSET utf8 NOT NULL,
    DESCRIPTION VARCHAR(1000) CHARSET utf8,
    USER_ID_ASSIGNEDTO BIGINT UNSIGNED NOT NULL,

    FOREIGN KEY (ISSUESLISTS_ID) REFERENCES issueslists(ID),
    FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS(ID)
);

INSERT INTO issueslists (NAME) VALUES ('ToDo');
INSERT INTO issueslists (NAME) VALUES ('In progress');
INSERT INTO issueslists (NAME) VALUES ('Done');

INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, 'Task ToDo1', 'First task in ToDo table', 2);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, 'Task ToDo2', 'Second task in ToDo table', 1);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, 'Task ToDo3', 'Third task in ToDo table', 1);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, 'Task ToDo4', 'Fourth task in ToDo table', 4);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (1, 'Task ToDo5', 'Fifth task in ToDo table', 3);

INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, 'Task InProgress1', 'First task in InProgress table', 1);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, 'Task InProgress2', 'Second task in InProgress table', 3);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, 'Task InProgress3', 'Third task in InProgress table', 4);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, 'Task InProgress4', 'Fourth task in InProgress table', 2);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (2, 'Task InProgress5', 'Fifth task in InProgress table', 1);

INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, 'Task Done1', 'First task in Done table', 1);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, 'Task Done2', 'Second task in Done table', 1);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, 'Task Done3', 'Third task in Done table', 4);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, 'Task Done4', 'Fourth task in Done table', 4);
INSERT INTO ISSUES (ISSUESLISTS_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) VALUES (3, 'Task Done5', 'Fifth task in Done table', 2);

COMMIT;

SELECT * FROM ISSUESLISTS;

SELECT * FROM ISSUES;