SELECT I.SUMMARY, I.DESCRIPTION, L.NAME
FROM ISSUES I
JOIN ISSUESLISTS L ON I.ISSUESLISTS_ID = L.ID;

SELECT U.FIRSTNAME, U.LASTNAME, I.SUMMARY, I.DESCRIPTION
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
ORDER BY U.LASTNAME, U.FIRSTNAME;

SELECT U.LASTNAME, U.FIRSTNAME, COUNT(*) AS TASKS_QUANTITY
FROM USERS U
JOIN ISSUES I ON I.USER_ID_ASSIGNEDTO = U.ID
GROUP BY U.ID
ORDER BY U.LASTNAME, U.FIRSTNAME;
