DROP PROCEDURE IF EXISTS FindUserById;

DELIMITER $$
CREATE PROCEDURE FindUserById(userId INT)
BEGIN
    IF userId > 0 THEN
        SELECT FIRSTNAME, LASTNAME, PESELID FROM READERS WHERE READER_ID = userId;
    ELSE
        SELECT 'USER DOESNT EXISTS' FROM READERS LIMIT 1;
    END IF;
END $$
DELIMITER ;

CALL FindUserById(1);

